import { ethers } from "ethers";
import * as fs from "fs";
import * as path from "path";

/**
 * Generates a fresh set of wallets and writes them into an env file.
 *
 *   npx ts-node scripts/new-wallets.ts                  -> .env         (testnet)
 *   ENV_FILE=.env.mainnet NETWORK=mainnet \
 *     npx ts-node scripts/new-wallets.ts                -> .env.mainnet
 *
 * One deployer/operator, four price reporters (the engine needs quotes from
 * distinct keys or cross-source consistency proves nothing — the numbering
 * matches the roster in keeper/index.ts), and a few participant wallets.
 *
 * Only the deployer needs external funding; `scripts/fund-wallets.ts`
 * distributes onward from it.
 *
 * Refuses to overwrite an existing file. Private keys are written to disk and
 * never printed, so they stay out of terminal scrollback, logs and screenshots.
 */

const ROLES = [
  { key: "DEPLOYER_PRIVATE_KEY", label: "deployer / operator" },
  // Numbering matches keeper/index.ts, which drives REPORTER_KEY_1..4.
  { key: "REPORTER_KEY_1", label: "price source — Binance" },
  { key: "REPORTER_KEY_2", label: "price source — OKX" },
  { key: "REPORTER_KEY_3", label: "price source — Pyth" },
  { key: "REPORTER_KEY_4", label: "price source — Gate.io" },
  { key: "INVESTOR_KEY_0", label: "participant 0" },
  { key: "INVESTOR_KEY_1", label: "participant 1" },
  { key: "INVESTOR_KEY_2", label: "participant 2" },
];

function main() {
  const root = path.join(__dirname, "..");
  const envFile = process.env.ENV_FILE ?? ".env";
  const isMainnet = (process.env.NETWORK ?? "").toLowerCase() === "mainnet";
  const envPath = path.join(root, envFile);

  if (fs.existsSync(envPath)) {
    throw new Error(`${envFile} already exists — refusing to overwrite. Move it aside first.`);
  }

  const wallets = ROLES.map((r) => ({ ...r, wallet: ethers.Wallet.createRandom() }));
  const deployer = wallets[0].wallet;
  const participants = wallets.filter((w) => w.key.startsWith("INVESTOR"));

  const header = isMainnet
    ? [
        "# ---------------------------------------------------------------------------",
        "# GENERATED by scripts/new-wallets.ts — BNB CHAIN MAINNET.",
        "#",
        "# These keys are stored in PLAINTEXT on this machine. Anyone who can read this",
        "# file controls the deployment: they can pause markets, register assets, and",
        "# mint against attested reserves.",
        "#",
        "# Acceptable for a grant deployment holding nominal value. Before this system",
        "# holds material assets, move DEFAULT_ADMIN_ROLE to a multisig and rotate the",
        "# operator key into a proper signer.",
        "#",
        "# Never commit, paste, screenshot, or send this file to anyone.",
        "# ---------------------------------------------------------------------------",
        "",
      ]
    : [
        "# ---------------------------------------------------------------------------",
        "# GENERATED by scripts/new-wallets.ts — TESTNET USE ONLY.",
        "#",
        "# Disposable keys in plaintext: fine for BSC testnet, NEVER for mainnet or any",
        "# wallet that will hold real value.",
        "#",
        "# This file is gitignored. Do not commit it, paste it, or screenshot it.",
        "# ---------------------------------------------------------------------------",
        "",
      ];

  const lines = [...header];
  for (const w of wallets) {
    lines.push(`# ${w.label} -> ${w.wallet.address}`);
    lines.push(`${w.key}=${w.wallet.privateKey}`);
  }

  lines.push(
    "",
    "# Admin, operator and treasury. Point ADMIN_ADDRESS at a multisig when one exists;",
    "# left unset, deploy.ts uses the deployer for all three.",
    `ADMIN_ADDRESS=${deployer.address}`,
    `TREASURY_ADDRESS=${deployer.address}`,
    `CUSTODIAN_ADDRESS=${deployer.address}`,
    "",
    "# Networks",
    isMainnet
      ? "BSC_RPC=https://bsc-dataseed.bnbchain.org"
      : "BSC_TESTNET_RPC=https://data-seed-prebsc-1-s1.bnbchain.org:8545",
    "",
    "# One Etherscan V2 key covers BscScan: https://etherscan.io/myapikey",
    "ETHERSCAN_API_KEY=",
    ""
  );

  if (isMainnet) {
    lines.push(
      "# Mainnet seasoning is the listing safety property — deploy.ts REFUSES to run on",
      "# chain 56 if SEASONING_PERIOD or REQUIRED_VALIDATIONS are set. Do not add them.",
      "",
      "# Keeper",
      "KEEPER_NETWORK=bsc",
      "KEEPER_INTERVAL_MS=300000",
      ""
    );
  } else {
    lines.push(
      "# Faster seasoning for a testnet rehearsal only.",
      "SEASONING_PERIOD=300",
      "REQUIRED_VALIDATIONS=3",
      "BOND_AMOUNT=0.01",
      "",
      "# Keeper",
      "KEEPER_NETWORK=bscTestnet",
      "KEEPER_INTERVAL_MS=300000",
      ""
    );
  }

  lines.push(
    "BINANCE_SYMBOL=PAXGUSDT",
    "OKX_INST_ID=PAXG-USDT",
    "GATE_PAIR=PAXG_USDT",
    "",
    "# Business flow participants",
    `USER_PRIVATE_KEYS=${participants.map((p) => p.wallet.privateKey).join(",")}`,
    "RESERVE_UNITS=500",
    "MINT_UNITS=10",
    "RUN_REDEMPTION=false",
    ""
  );

  fs.writeFileSync(envPath, lines.join("\n"), { mode: 0o600 });

  console.log(`wrote ${envPath} (private keys on disk only, never printed)\n`);
  console.log(`network: ${isMainnet ? "BNB Chain MAINNET" : "BSC testnet"}\n`);
  console.log("addresses:");
  for (const w of wallets) {
    console.log(`  ${w.wallet.address}  ${w.label}`);
  }
  console.log(`\n>>> FUND THIS ONE <<<\n\n    ${deployer.address}\n`);
  if (isMainnet) {
    console.log("    Suggested: 0.5 BNB (deploy ~0.0006, keeper ~0.25/month, rest buffer)");
    console.log("    Then:  DEPLOYER_RESERVE=0.05 npx ts-node scripts/fund-wallets.ts");
  } else {
    console.log("    https://www.bnbchain.org/en/testnet-faucet");
    console.log("    Then:  npx ts-node scripts/fund-wallets.ts");
  }
}

main();
